package com.johnchourp.learnbyzantinemusic.anastasimatarion

import android.content.Context
import org.json.JSONObject

/**
 * «Αναστασιματάριο» — the Sunday resurrection hymns of the eight modes, with the user's own
 * recordings kept per hymn.
 *
 * The catalog is the asset `anastasimatarion_v1.json`, generated by
 * `scripts/generate-anastasimatarion-catalog.mjs` from the Octoechos Sunday texts. It stores only
 * each hymn's incipit, grouped mode → service (Εσπερινός / Όρθρος / Θεία Λειτουργία) → group
 * (Στιχηρά Αναστάσιμα, Απόστιχα …).
 *
 * The asset carries **no source or URL**, and neither does the UI: the same confidential policy
 * the εορτολόγιο dataset follows (ClickUp `869dbkkwf`, decided 2026-09-22). `AnastasimatarionAssetSchemaTest`
 * enforces it, so it cannot come back by accident.
 *
 * Every hymn has a two-digit [Hymn.code], unique within its mode and stable across catalog
 * versions: [HymnFolders] names a hymn's recordings folder after it, so a code must never be
 * reused for a different hymn.
 */
data class Hymn(
    val code: String,
    val incipit: String,
    val note: String?,
)

data class HymnGroup(val key: String, val hymns: List<Hymn>)

data class HymnService(val key: String, val groups: List<HymnGroup>)

data class HymnMode(val key: String, val services: List<HymnService>) {
    val hymns: List<Hymn>
        get() = services.flatMap { service -> service.groups.flatMap { it.hymns } }

    /** The hymn with [code] together with its service and group, or null. */
    fun find(code: String): HymnRef? {
        for (service in services) {
            for (group in service.groups) {
                val hymn = group.hymns.firstOrNull { it.code == code } ?: continue
                return HymnRef(modeKey = key, serviceKey = service.key, groupKey = group.key, hymn = hymn)
            }
        }
        return null
    }
}

data class HymnCatalog(
    val modes: List<HymnMode>,
) {
    fun mode(key: String): HymnMode? = modes.firstOrNull { it.key == key }
}

/** A hymn together with where it sits in the catalog. */
data class HymnRef(
    val modeKey: String,
    val serviceKey: String,
    val groupKey: String,
    val hymn: Hymn,
)

object AnastasimatarionCatalogParser {
    fun parse(json: String): HymnCatalog {
        val root = JSONObject(json)
        val modesJson = root.getJSONArray("modes")
        val modes = (0 until modesJson.length()).map { modeIndex ->
            val modeJson = modesJson.getJSONObject(modeIndex)
            val servicesJson = modeJson.getJSONArray("services")
            HymnMode(
                key = modeJson.getString("key"),
                services = (0 until servicesJson.length()).map { serviceIndex ->
                    val serviceJson = servicesJson.getJSONObject(serviceIndex)
                    val groupsJson = serviceJson.getJSONArray("groups")
                    HymnService(
                        key = serviceJson.getString("key"),
                        groups = (0 until groupsJson.length()).map { groupIndex ->
                            val groupJson = groupsJson.getJSONObject(groupIndex)
                            val hymnsJson = groupJson.getJSONArray("hymns")
                            HymnGroup(
                                key = groupJson.getString("key"),
                                hymns = (0 until hymnsJson.length()).map { hymnIndex ->
                                    val hymnJson = hymnsJson.getJSONObject(hymnIndex)
                                    Hymn(
                                        code = hymnJson.getString("code"),
                                        incipit = hymnJson.getString("incipit"),
                                        note = hymnJson.optString("note").takeIf { it.isNotBlank() },
                                    )
                                },
                            )
                        },
                    )
                },
            )
        }
        return HymnCatalog(
            modes = modes,
        )
    }
}

object AnastasimatarionCatalogLoader {
    const val ASSET_NAME = "anastasimatarion_v1.json"

    @Volatile
    private var cached: HymnCatalog? = null

    /** Parses the bundled catalog once per process; call off the main thread. */
    fun load(context: Context): HymnCatalog {
        cached?.let { return it }
        return synchronized(this) {
            cached ?: context.applicationContext.assets.open(ASSET_NAME).bufferedReader(Charsets.UTF_8).use { reader ->
                AnastasimatarionCatalogParser.parse(reader.readText())
            }.also { cached = it }
        }
    }
}
